# Generated by Django 4.2.7 on 2025-12-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menucategory",
            name="couple",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.couple",
                verbose_name="所属情侣",
            ),
        ),
    ]
