# Generated by Django 4.2.7 on 2025-12-31 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
        ("menu", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menucategory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
        migrations.AlterField(
            model_name="menucategory",
            name="couple",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.couple",
                verbose_name="所属情侣",
            ),
        ),
    ]
