# Generated by Django 4.2.7 on 2025-12-31 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("memo", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="couple",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.couple",
                verbose_name="所属情侣",
            ),
        ),
    ]
