# Generated by Django 4.2.7 on 2025-12-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PushLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "db_table": "push_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_id",
                    models.CharField(max_length=100, verbose_name="模板ID"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="推送标题")),
                ("content", models.TextField(verbose_name="推送内容")),
                ("push_time", models.DateTimeField(verbose_name="推送时间")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="是否已推送"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际推送时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "db_table": "push_task",
                "ordering": ["-created_at"],
            },
        ),
    ]
