# Generated by Django 4.2.7 on 2025-12-31 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("push", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushtask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收用户",
            ),
        ),
        migrations.AddField(
            model_name="pushlog",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="push.pushtask",
                verbose_name="推送任务",
            ),
        ),
    ]
